import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = process.cwd();
const ENV_PATH = resolve(ROOT, '.env');
const OUTPUT_PATH = resolve(ROOT, 'src/environments/environment.generated.ts');

const REQUIRED_KEYS = [
  'VITE_LOGIN_ENDPOINT',
  'VITE_LOGOUT_ENDPOINT',
  'VITE_REFRESH_ENDPOINT',
  'VITE_REGISTER_ENDPOINT',
  'VITE_GET_FRIENDS_REQUEST_ENDPOINT',
  'VITE_SEND_FRIEND_REQUEST_ENDPOINT',
  'VITE_RESPONSE_FRIEND_REQUEST_ENDPOINT',
  'VITE_CREATE_TRANSACTION_ENDPOINT',
  'VITE_GET_TRANSACTION_ENDPOINT',
  'VITE_FINISH_TRANSACTION_ENDPOINT',
  'VITE_CREATE_EXPENSE_ENDPOINT',
  'VITE_GET_EXPENSE_ENDPOINT'
];

function parseDotEnv(content) {
  const env = {};
  const lines = content.split(/\r?\n/);

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (!line || line.startsWith('#')) {
      continue;
    }

    const equalIndex = line.indexOf('=');
    if (equalIndex <= 0) {
      continue;
    }

    const key = line.slice(0, equalIndex).trim();
    let value = line.slice(equalIndex + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

if (!existsSync(ENV_PATH)) {
  throw new Error('Missing .env file at project root.');
}

const parsed = parseDotEnv(readFileSync(ENV_PATH, 'utf8'));
const missing = REQUIRED_KEYS.filter((key) => !parsed[key]);

if (missing.length > 0) {
  throw new Error(`Missing required .env keys: ${missing.join(', ')}`);
}

const generated = `// Auto-generated by scripts/generate-env.mjs. Do not edit manually.\n` +
`export const viteEnv = {\n` +
REQUIRED_KEYS.map((key) => `  ${key}: ${JSON.stringify(parsed[key])},`).join('\n') +
`\n} as const;\n`;

writeFileSync(OUTPUT_PATH, generated, 'utf8');
console.log(`Generated ${OUTPUT_PATH}`);
